import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vite-plus';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const pkg = JSON.parse(readFileSync(resolve(__dirname, 'package.json'), 'utf8')) as {
  version: string;
};
const sourceOnlyIgnorePatterns = ['**/*', '!src', '!src/**'];

// `vp run check` sends `vp check`'s output to a redirect FILE instead of letting it
// write straight to the run-task pipe, and prints it only when the check FAILS.
// The Rust oxc binary PANICS mid-write once its output gets large — "failed printing
// to stdout: Resource temporarily unavailable" (os error 11 on Linux, 35 on macOS) —
// aborting the task with exit 134 even though the check itself finds 0 ERRORS. `vp run`
// hands a task a NON-BLOCKING stdout pipe, so a large write hits EAGAIN; a regular file
// is blocking I/O and never does. #1761: reproduced 3/3 on a clean `main` at ~117
// warnings, while `vp run lint` (longer output, but not the combined lint+format path)
// did NOT panic — hence the workaround is scoped to `check`.
// `.github/workflows/ci.yml` applies the same trick for the same reason; keep the two in
// sync. The `exit 1` is unconditional, so a real lint/format ERROR still surfaces (with
// the full captured output) and still exits non-zero. On success nothing is printed —
// run `vp check` directly to read the advisory warning list.
// The log lives under `node_modules/` so it can never be swept into a commit by
// `git add -A`; the task does not cache either way (vite's own
// `node_modules/.vite-temp/vite.config.ts.timestamp-*.mjs` already makes every `vp run`
// task here a cache miss).
const checkLogDir = 'node_modules/.cache';
const checkLog = `${checkLogDir}/vpcheck.log`;
const checkCommand = [
  `mkdir -p ${checkLogDir}`,
  `vp check >${checkLog} 2>&1 || { cat ${checkLog}; exit 1; }`,
].join(' && ');

export default defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },

  test: {
    globals: true,
    environment: 'node',
    // Arm Node's diagnostic report on the forks workers so a fatal/uncaught
    // crash writes report.*.json (dumped by .github/workflows/ci.yml on
    // failure). No overhead on a clean run. Mirrors cdk-local.
    pool: 'forks',
    poolOptions: {
      forks: {
        execArgv: ['--report-on-fatalerror', '--report-uncaught-exception'],
      },
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: [
        'node_modules/**',
        'dist/**',
        '**/*.config.ts',
        '**/*.d.ts',
        'tests/**',
        'vite.config.ts',
      ],
    },
    include: ['tests/**/*.test.ts', 'src/**/*.test.ts'],
    exclude: ['node_modules', 'dist', 'tests/integration/**'],
  },

  lint: {
    env: {
      node: true,
      es2022: true,
      vitest: true,
    },
    plugins: ['typescript', 'promise', 'vitest', 'eslint'],
    ignorePatterns: [...sourceOnlyIgnorePatterns, '!tests', '!tests/**', 'tests/integration/**'],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    rules: {
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      'no-console': 'off',
    },
  },

  fmt: {
    semi: true,
    trailingComma: 'es5',
    singleQuote: true,
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    arrowParens: 'always',
    endOfLine: 'lf',
    sortPackageJson: false,
    // CHANGELOG.md is machine-generated by @semantic-release/changelog on every
    // release and committed verbatim (see .releaserc.json); its markdown is not
    // prettier-clean (extra blank lines around headings), so formatting it would
    // make `vp run check` in CI fail on the release commit's output. Exclude it —
    // cdk-local/cdkd achieve the same by scoping fmt to src only.
    ignorePatterns: ['tests/integration/**', 'CHANGELOG.md'],
  },

  pack: {
    entry: {
      cli: 'src/cli.ts',
    },
    outDir: 'dist',
    platform: 'node',
    target: 'node20',
    format: 'esm',
    fixedExtension: false,
    dts: false,
    sourcemap: true,
    minify: false,
    define: {
      __CDKRD_VERSION__: JSON.stringify(pkg.version),
    },
    deps: {
      neverBundle: [/^@aws-sdk\//, 'yaml'],
    },
  },

  run: {
    cache: {
      tasks: true,
    },
    tasks: {
      build: { command: 'vp pack', cache: false },
      dev: { command: 'vp pack --watch', cache: false },
      check: { command: checkCommand },
      test: { command: 'vp test run' },
      'test:watch': { command: 'vp test watch', cache: false },
      'test:coverage': { command: 'vp test run --coverage', cache: false },
      lint: { command: 'vp lint' },
      'lint:fix': { command: 'vp lint --fix', cache: false },
      format: { command: 'vp fmt', cache: false },
      'format:check': { command: 'vp fmt --check' },
      // The `.claude/hooks/*.test.sh` harnesses assert the gates' BLOCK / ALLOW
      // contracts. Nothing ran them until 2026-08-20
      // (go-to-k/cdk-real-drift#1797) — they are shell, so `vp test run` never
      // saw them, and CI had no step. cache:false: their subjects are hook
      // scripts and settings.json, which the task hash does not cover.
      'test:hooks': { command: 'bash scripts/run-hook-tests.sh', cache: false },
      // cache:false — the run-task cache can REPLAY a stale pass even though the
      // current tree has a real type error, masking it. This bit us live: PR #438
      // introduced a duplicate object-literal key (tsgo TS1117) that `vp run
      // typecheck` reported GREEN from cache, so the gate marker was set on a red
      // tree and the break reached main. Typecheck is ~1s; correctness > the cache.
      typecheck: { command: 'tsc --project tsconfig.json --noEmit', cache: false },
      verify: { command: 'vp run check && vp run test && vp run test:hooks && vp run build' },
      'runtime:smoke': {
        command: 'node dist/cli.js --version',
        dependsOn: ['build'],
        cache: false,
      },
    },
  },
});
