import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vite-plus/test';

// Guard against `vp fmt` silently CORRUPTING committed markdown prose.
//
// ROOT CAUSE (traced 2026-08-19, #1771): `vp fmt` -> oxfmt, which delegates
// MARKDOWN to a vendored Prettier. `vite-plus` 0.1.24 pins oxfmt 0.52.0, which
// bundles Prettier 3.8.3 — and pre-3.9 Prettier mis-pairs a `**` bold opener with
// a `**` that lives INSIDE an inline code span (prettier#15032 / prettier#19016,
// fixed by the micromark upgrade in prettier#18277, shipped in Prettier 3.9.0).
// The mis-parse turns intervening prose into a phantom code span, so the spaces
// around later code spans are EATEN and continuation lines lose their indent:
//
//   in : - **bold (`src/**` here)** then `tests/**` and `word` after.
//   out: - **bold (`src/**`here)** then`tests/\*\*`and`word` after.
//
// It is ONE-SHOT (passes 2 and 3 leave the mangled text alone), which is exactly
// what makes it dangerous: the damage NEVER self-repairs, and it arrives from
// `--fix` AFTER the author has read their own text. #1766 shipped a mangled
// paragraph into `.claude/skills/work-issues/SKILL.md` this way, and commit
// fe64665 (PR #405) shipped one into `docs/ARCHITECTURE.md` that survived
// 1098 commits until #1771.
//
// This matters because the blast radius is agent-instruction prose, which nothing
// else lints — a mangled sentence is still valid markdown, so every other gate is
// green while the text an agent ACTS on has quietly lost its word boundaries.
//
// The real fix is a toolchain bump to `vite-plus` >= 0.2.5 (the first release
// pinning an oxfmt whose Prettier is >= 3.9.4), shipped as #1780. These checks
// stay useful after that bump, because they assert the PROPERTY (prose is not
// mangled) rather than the version — and the round-trip block at the bottom runs
// the live formatter, so a future downgrade reds the tree before shipping damage.
//
// Every threshold below is calibrated against the real corrupt tree: measured on
// the pre-repair `docs/ARCHITECTURE.md`, LEFT-glue found 5 hits and ALL 5 were
// genuine corruption, while RIGHT-glue found 13 of which 6 were the legitimate
// plural-`s` suffix (`` `remove`s ``). Hence the asymmetric rules.

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// CHANGELOG.md is machine-generated by release-please from commit subjects and
// rewritten wholesale on every release. A finding there is not hand-fixable and
// would red the tree on `main` with no way to land a repair, so it is out of scope.
const EXCLUDED = new Set(['CHANGELOG.md']);

function markdownFiles(): string[] {
  return execSync('git ls-files "*.md"', { cwd: ROOT, encoding: 'utf8' })
    .trim()
    .split('\n')
    .filter((f) => f && !EXCLUDED.has(f));
}

/** Blank-line-separated prose blocks, with fenced code blocks removed. */
export function proseParagraphs(text: string): Array<{ line: number; body: string }> {
  const out: Array<{ line: number; body: string }> = [];
  let fenced = false;
  let buf: string[] = [];
  let start = 0;
  const flush = () => {
    if (buf.length) out.push({ line: start, body: buf.join('\n') });
    buf = [];
  };
  text.split('\n').forEach((line, i) => {
    if (/^\s*(```|~~~)/.test(line)) {
      flush();
      fenced = !fenced;
      return;
    }
    if (fenced) return;
    if (!line.trim()) {
      flush();
      return;
    }
    if (!buf.length) start = i + 1;
    buf.push(line);
  });
  flush();
  return out;
}

interface Hit {
  /** Offset of the finding within the paragraph, used to recover its line. */
  at: number;
  text: string;
}

interface Span {
  raw: string;
  content: string;
  index: number;
  before: string;
  after: string;
}

/**
 * Inline code spans of a paragraph, scanned left-to-right so backtick pairing is
 * correct. Paragraph scope (not per line) matters: a code span may WRAP across a
 * line break, and a per-line scan mis-pairs the halves into phantom spans.
 */
function codeSpans(paragraph: string): Span[] {
  const out: Span[] = [];
  const re = /(`+)([\s\S]*?)\1/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(paragraph)) !== null) {
    out.push({
      raw: m[0],
      content: m[2],
      index: m.index,
      before: m.index > 0 ? paragraph[m.index - 1] : '',
      after: paragraph[m.index + m[0].length] ?? '',
    });
  }
  return out;
}

/**
 * The DAMAGE signature: a code span whose surrounding space the formatter ate.
 *
 * LEFT (a letter immediately BEFORE the span) is flagged unconditionally — prose
 * essentially never runs a word straight into a code span, and all 5 occurrences
 * in the corrupt tree were real.
 *
 * RIGHT (a letter immediately AFTER) allows a short English suffix, which IS
 * idiomatic here: `` `remove`s ``, `` `CANDIDATE`s ``, `` `record`s ``.
 */
export function glueDamage(paragraph: string): Hit[] {
  const hits: Hit[] = [];
  for (const s of codeSpans(paragraph)) {
    if (/[A-Za-z]/.test(s.before)) hits.push({ at: s.index, text: `${s.before}${s.raw}` });
    if (/[A-Za-z]/.test(s.after)) {
      const trailing = paragraph.slice(s.index + s.raw.length);
      const isSuffix = /^(s|es)(?![A-Za-z])/.test(trailing);
      if (!isSuffix) hits.push({ at: s.index, text: `${s.raw}${s.after}` });
    }
  }
  return hits;
}

/**
 * The TRIGGER construct: a code span containing `**` that sits inside an OPEN bold
 * run — i.e. an odd number of bold delimiters precede it, counting only `**` that
 * lie OUTSIDE code spans. Verified against a 9-case live `vp fmt` probe matrix.
 *
 * This signature PERSISTS through the corruption (the offending span survives in
 * place), so it catches both a paragraph about to be mangled and one already
 * mangled — unlike the damage signature, which only appears afterwards.
 */
export function boldGlobHazard(paragraph: string): Hit[] {
  const hits: Hit[] = [];
  let bolds = 0;
  const re = /(`+)([\s\S]*?)\1|\*\*/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(paragraph)) !== null) {
    if (m[0] === '**') {
      bolds++;
      continue;
    }
    if (m[2].includes('**') && bolds % 2 === 1) hits.push({ at: m.index, text: m[0] });
  }
  return hits;
}

function scan(check: (p: string) => Hit[]): string[] {
  const findings: string[] = [];
  for (const file of markdownFiles()) {
    for (const { line, body } of proseParagraphs(readFileSync(path.join(ROOT, file), 'utf8'))) {
      for (const hit of check(body)) {
        // Report the line the hit is ON, not the paragraph start — a paragraph
        // here can run 100+ lines, and a start-of-paragraph number sends the
        // reader hunting for text that is nowhere near it.
        const line0 = line + body.slice(0, hit.at).split('\n').length - 1;
        findings.push(`${file}:${line0}  ${hit.text}`);
      }
    }
  }
  return findings;
}

describe('vp fmt markdown corruption (#1771)', () => {
  it('no committed markdown carries the space-eaten damage signature', () => {
    expect(scan(glueDamage)).toEqual([]);
  });

  it('no committed markdown carries the bold-plus-**-in-code-span trigger', () => {
    expect(scan(boldGlobHazard)).toEqual([]);
  });

  // Lock the detectors themselves to the observed `vp fmt` behavior, so a future
  // refactor cannot quietly turn either scan into a no-op that reports [] forever.
  describe('trigger detector, against the recorded live probe matrix', () => {
    const CORRUPTS = [
      '- **bold (`src/**` here)** then `tests/**` and `word` after.',
      '- **bold (`src/**` here)**',
      '**bold (`src/**` here)** then `tests/**` and `word` after.',
    ];
    const SAFE = [
      '- plain (`src/**` here) then `tests/**` and `word` after.',
      '- **bold (`src/` here)** then `tests/` and `word` after.',
      '- plain `src/**` then **bold** and `word` after.',
      '- **bold (`src/*` here)** then `tests/*` and `word` after.',
      '- _ital (`src/**` here)_ then `tests/**` and `word` after.',
      '- **After changing** `src/read/**`, `src/revert/**`, or more.',
    ];
    it.each(CORRUPTS)('flags %j', (p) => expect(boldGlobHazard(p)).not.toEqual([]));
    it.each(SAFE)('leaves %j alone', (p) => expect(boldGlobHazard(p)).toEqual([]));

    it('still flags the paragraph AFTER vp fmt has mangled it', () => {
      expect(
        boldGlobHazard('- **bold (`src/**`here)** then`tests/\\*\\*`and`word` after.')
      ).not.toEqual([]);
    });
  });

  describe('damage detector', () => {
    it.each([
      'ONLY when stdout is a real TTY and`NO_COLOR`is unset.',
      'the`info:`footer) uses the`note`helper = the terminal DEFAULT foreground',
      'Piped / CI /`--json`output is byte-identical plain text',
      'not mislabeled confirmed drift:`--show-all --fail`does not exit 1',
    ])('flags the real shipped corruption %j', (p) => expect(glueDamage(p)).not.toEqual([]));

    it.each([
      'sibling `remove`s ride the same patch',
      'the constant-looking ones as `CANDIDATE`s to promote',
      'Enables acceleration, `record`s (recording the undeclared value)',
      'a bold `result:` label framed by a horizontal rule',
    ])('leaves idiomatic prose %j alone', (p) => expect(glueDamage(p)).toEqual([]));

    it('scans per paragraph so a code span wrapping a line break is not mis-paired', () => {
      // A per-LINE scan pairs the closing backtick of one span with the opening
      // backtick of the next and reports a phantom hit on the prose between them.
      expect(
        glueDamage(
          'run BY HAND (`bash\n.claude/hooks/x.test.sh` from the root) — nothing in `vp test run` or CI'
        )
      ).toEqual([]);
    });
  });

  // The two scans above only see COMMITTED damage — they fire one gate cycle
  // AFTER a buggy formatter has already mangled and shipped a file. This block
  // runs the formatter itself, so a downgrade below the fix boundary
  // (`vite-plus` >= 0.2.5, the first release whose oxfmt bundles Prettier
  // >= 3.9.4 — #1780) turns the tree red BEFORE any prose is touched.
  describe('the formatter itself round-trips the trigger construct (#1780)', () => {
    it('vp fmt is a no-op on the recorded repro line, twice in a row', () => {
      const repro = '- **bold (`src/**` here)** then `tests/**` and `word` after.\n';
      const dir = mkdtempSync(path.join(tmpdir(), 'cdkrd-fmt-1780-'));
      const file = path.join(dir, 'repro.md');
      try {
        writeFileSync(file, repro);
        // Twice: the corruption is ONE-SHOT (pass 2 leaves mangled text alone),
        // so a single no-op pass could in principle be the quiet second pass.
        for (let pass = 0; pass < 2; pass++) {
          execSync(`vp fmt ${JSON.stringify(file)}`, { cwd: ROOT, stdio: 'pipe' });
          expect(readFileSync(file, 'utf8')).toBe(repro);
        }
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    });
  });
});
