// CDK app for the cdk-real-drift appsync-resolver-rich false-positive integration
// test. The appsync-graphqlapi-rich fixture stresses the GraphqlApi body; this one
// stresses the DECLARED child resources a large fraction of AppSync users deploy and
// that are not yet in the golden corpus: a DynamoDB DataSource, two UNIT Resolvers
// with VTL request/response MappingTemplates, a Function (FunctionConfiguration), and
// a PIPELINE Resolver wiring that function. VTL templates are multi-line text blobs
// AppSync may echo with added/stripped whitespace, so a clean `record`->`check` is a
// strong false-positive oracle for whitespace coercion on Request/ResponseMappingTemplate.
// All three child types (Resolver / FunctionConfiguration / DataSource) are Cloud
// Control-readable, so the live reads harvest as fresh golden-corpus cases.
import { fileURLToPath } from "node:url";
import { App, RemovalPolicy, Stack } from "aws-cdk-lib";
import {
  AttributeType,
  BillingMode,
  Table,
} from "aws-cdk-lib/aws-dynamodb";
import {
  AppsyncFunction,
  Definition,
  GraphqlApi,
  MappingTemplate,
  PrimaryKey,
  Values,
} from "aws-cdk-lib/aws-appsync";

const app = new App();
const stack = new Stack(app, "CdkRealDriftIntegAppsyncResolverRich");

const schemaPath = fileURLToPath(new URL("./schema.graphql", import.meta.url));

const api = new GraphqlApi(stack, "Api", {
  name: "cdkrd-appsync-resolver-rich",
  definition: Definition.fromFile(schemaPath),
});

const table = new Table(stack, "Items", {
  partitionKey: { name: "id", type: AttributeType.STRING },
  billingMode: BillingMode.PAY_PER_REQUEST,
  removalPolicy: RemovalPolicy.DESTROY,
});

const ds = api.addDynamoDbDataSource("ItemsDs", table);

// Two UNIT resolvers: each carries a multi-line VTL request + response template
// generated by the CDK helpers (valid VTL AppSync round-trips).
ds.createResolver("GetItemResolver", {
  typeName: "Query",
  fieldName: "getItem",
  requestMappingTemplate: MappingTemplate.dynamoDbGetItem("id", "id"),
  responseMappingTemplate: MappingTemplate.dynamoDbResultItem(),
});

ds.createResolver("PutItemResolver", {
  typeName: "Mutation",
  fieldName: "putItem",
  requestMappingTemplate: MappingTemplate.dynamoDbPutItem(
    PrimaryKey.partition("id").auto(),
    Values.projecting(),
  ),
  responseMappingTemplate: MappingTemplate.dynamoDbResultItem(),
});

// A Function + a PIPELINE resolver wiring it (FunctionConfiguration corpus + pipeline
// kind Resolver — its PipelineConfig.Functions is a Function-id list). The pipeline
// resolver's before/after templates are hand-written multi-line VTL via fromString —
// the deliberate whitespace-coercion probe (leading indentation + a trailing newline
// AppSync may add or strip).
const fn = new AppsyncFunction(stack, "ListFn", {
  api,
  dataSource: ds,
  name: "listItemsFn",
  requestMappingTemplate: MappingTemplate.dynamoDbScanTable(),
  responseMappingTemplate: MappingTemplate.dynamoDbResultList(),
});

api.createResolver("ListItemsResolver", {
  typeName: "Query",
  fieldName: "listItems",
  pipelineConfig: [fn],
  requestMappingTemplate: MappingTemplate.fromString(
    "## before pipeline\n{\n  \"version\": \"2018-05-29\"\n}\n",
  ),
  responseMappingTemplate: MappingTemplate.fromString(
    "## after pipeline\n$util.toJson($ctx.result)\n",
  ),
});

app.synth();
